### ISSUE TITLE
would it be possible to make a docker container that contained the packages and source so you could build it from inside the container ?

### ISSUE THREAD

**Issue by robertnax** [Hetsh/docker-umurmur#2]
thanks for your image, it works smooth.

what i would like though was to be able to build the source - i have given up being able to understand the wiki of building it, i simply cannot get it buildt on ubuntu ( its abit too technical with the build process for me ).

But wondered if it was possible to have a container where you could run CMake within and it would just compile it all ?

**Comment by Hetsh** [comment]
Glad you find it useful.

I only use precompiled binaries from the alpine linux repositories and have no experience in building uMurmur from source.
Usually the source is compiled during dockers build stage, so you might be able to copy the steps from someone else.
Maybe you can adapt [gp3t1's Dockerfile](https://github.com/gp3t1/umurmur-docker/blob/master/Dockerfile) to Ubuntu?

**Comment by Hetsh** [comment]
Closed due to inactivity
